name: Merge on main
on:
  pull_request:
    branches:
      - main
    types: [closed]

jobs:
  deploy:
    # Setup OS and Node Version
    runs-on: ubuntu-latest

    steps:
      # Checkout code
      - name: Checkout Code
        if: github.event.pull_request.merged == true && contains(github.event.commits[0].message, '[skip-ci]') == false
        uses: actions/checkout@v2

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: '16.x'

      - name: Fetch other branches
        run: git fetch --no-tags --prune --depth=5 origin main

      - name: Install environment
        run: npm install

      - name: Configure npm
        run: |
          echo '//registry.npmjs.org/:_authToken=${NPM_TOKEN}' > .npmrc
          cat .npmrc
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}

      - name: Deploy
        if: github.event.pull_request.merged == true && contains(github.event.commits[0].message, '[skip-ci]') == false
        env:
          NPM_AUTH_TOKEN: ${{ secrets.NPM_AUTH_TOKEN }}
        run: |
          npm config set //registry.npmjs.org/:_authToken=$NPM_AUTH_TOKEN
          ./.github/scripts/publish-libraries.sh

      # - name: Build Docs
      #   if: github.event.pull_request.merged == true && contains(github.event.commits[0].message, '[skip-ci]') == false
      #   run: npm run docs

      - name: Commit files
        if: github.event.pull_request.merged == true && contains(github.event.commits[0].message, '[skip-ci]') == false
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add .
          git commit -m "Release [skip-ci]" -a || true

      - name: Push changes
        if: github.event.pull_request.merged == true && contains(github.event.commits[0].message, '[skip-ci]') == false
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          tags: true
          force: true
