name: Release

on:
  - workflow_dispatch

jobs:
  deploy:
    # Setup OS and Node Version
    runs-on: ubuntu-latest

    steps:
      # Checkout code
      - name: Checkout Code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      # Install deps
      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16'

      - name: Setup Git
        run: |
          git config user.name "GitHub Bot"
          git config user.email "Brian-McBride@users.noreply.github.com"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}

      # - name: Configure npm
      #   run: |
      #     echo '//registry.npmjs.org/:_authToken=${NPM_TOKEN}' > .npmrc
      #   env:
      #     NPM_TOKEN: ${{ secrets.NPM_TOKEN }}

      - name: Install environment
        run: npm install

      - name: Test
        run: npm run test:affected

      - name: Version
        shell: bash
        run: npm run release:affected --base=last-release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
          
      - name: Tag last-release
        shell: bash
        run: |
          git tag -f last-release
          git push origin last-release --force


